### ISSUE TITLE
Create / config an Action that validates that a submodule contains the Catalog components

### ISSUE THREAD

**Issue by tangollama** [newrelic/nr1-catalog#1]
The specs for the catalog are described in detail [here](https://docs.google.com/document/d/1pS74GNZUVjDlzVxrl0e5o6afQRqSlPiXPcCAyGQh_HA/edit) and usage in the proposed UI is [here](https://docs.google.com/document/d/1m_THBPfH-bxQLRRxSwPd4GL8gw4S8_iCdM5K4yJi2kY/edit). 

We need:
- [x] a semantic version number in the [package.json](https://source.datanerd.us/nr1-dev-experience/metadata-example/blob/master/nr1.json)
- [x] an [nr1.json](https://source.datanerd.us/nr1-dev-experience/metadata-example/blob/master/nr1.json) file in the root of the submodule
- [x] an [icon.png](https://source.datanerd.us/nr1-dev-experience/metadata-example/blob/master/icon.png) file in the root of the submodule
- [x] a [catalog/config.json](https://source.datanerd.us/nr1-dev-experience/metadata-example/blob/master/catalog/config.json) file matching the linked format (containing at least two elements in the `support` subsection of the JSON)
- [x] at least one [screenshot](https://source.datanerd.us/nr1-dev-experience/metadata-example/tree/master/catalog/screenshots) in the `catalog/screenshots` directory

**Comment by jbeveland27** [comment]
[Files-present-action](urlhttps://github.com/newrelic/nr1-catalog/tree/master/.github/actions/files-present-action addresses all these requirements.
