### ISSUE TITLE
Remove the 3rd party JFR nerdlet from staging and archive the repo

### ISSUE THREAD

**Issue by jasonjkeller** [newrelic/nr1-catalog#116]
Currently, in the staging environment there are two JFR nerdlets available, the old [third party nerdlet](https://github.com/newrelic/nr1-jfr) and the [first party nerdlet](https://source.datanerd.us/java-agent/jfr-nerdlet) that replaced it.

We should remove the third party nerdlet from staging so that only the first party nerdlet is visible. We should also archive the nr1-jfr repo since it's been replaced.

@amit-y mentioned the following blocker which needs to be addressed before we can remove the nerdlet:

> we need to identify the accounts which have access to the older version, and then unsubscribe them. I have reached out to get a list of accounts that are currently subscribed through the backend, because there's no way to get that through the UI. I haven't heard anything back from that team. So, essentially we'd have to remember all the accounts that we enabled, and then go in and unsubscribe all of them.

**Comment by kittylyst** [comment]
Just bumping this issue. Could I get a status please?

**Comment by jasonjkeller** [comment]
@jbeveland27 What do you need from us to move this forward? We need to have this 3rd party nerdlet removed very soon before the 1st party version becomes generally available.

Previously you mentioned the following as holding this up. Is that still the case?

> But since the 3rd party has been available since 3/19/2020 (when it was made available in the Catalog), we're going to have to work with Platform Services to remove it from any accounts that already added it via the Catalog.

**Comment by jbeveland27** [comment]
The JFR Nerdlet is no longer global. Will need to do some internal work to get it removed from accounts.

Will follow up conversation in Slack.
