### ISSUE TITLE
Create / config an Action that validates the expected structure of an NR1 application

### ISSUE THREAD

**Issue by tangollama** [newrelic/nr1-catalog#3]
There are a number of commands and configurations that we're recommending / enforcing internally w/r/t to NR1 apps w/in New Relic. We want to be sure we're validating that these configurations exist so that we have the capability to execute things like `linting` commands further downstream in the process. 

- [x] README.md
- [x] .prettierrc.js
- [x] .eslintrc.js
- [x] .gitignore
- [x] .releaserc
- [x] package.json
- [x] LICENSE
- [x] THIRD_PARTY_NOTICES.md

In addition, the `package.json` should contain the following commands:

- [x] `scripts.eslint-check`
- [x] `scripts.eslint-fix`

See our current, standard [circleci config](https://github.com/newrelic/nr1-browser-analyzer/blob/master/.circleci/config.yml#L212-L245) as a pattern.

**Comment by jbeveland27** [comment]
[Files-present-action](https://github.com/newrelic/nr1-catalog/tree/master/.github/actions/files-present-action) addresses all these requirements.
