### ISSUE TITLE
EOL nr1-graphiql-notebook

### ISSUE THREAD

**Issue by aswanson-nr** [newrelic/nr1-catalog#313]
### Acceptance Criteria

- [x] Confirm with the programmability 🧙  that there are no concerns with removing this app. 
- [x] Follow the end of life process to[ remove this application from the catalog](https://github.com/newrelic/nr1-catalog/wiki/New-Relic-One-App-Catalog-How-To-Guide#removing-an-app-from-the-nr1-catalog)
- [x] Archive the repo

### Usage
<img width="1253" alt="Screen Shot 2022-02-23 at 11 19 11 AM" src="https://user-images.githubusercontent.com/1395158/155383436-0d9ebbf7-49b0-4166-afe3-e8ac448ca648.png">

**Comment by jpvajda** [comment]
I've let some people know our intentions to EOL this app just waiting back on any concerns, I've also changed the AC to be focused on the end of life steps we need to take.
