### ISSUE TITLE
Update nr1-quickstarts node version

### ISSUE THREAD

**Issue by aswanson-nr** [newrelic/nr1-catalog#325]
### Acceptance Criteria

- [ ] Upgrade to node 16
- [ ] If applicable resolve any app deprecations planned for march 1st. 
- [ ] set a [code owner ](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners)for this repository 
- [ ] update .nvrmc file to Node 16
- [ ] Confirm if we need to set the NODE_VERSION environment variable
- [ ] Ensure all documentation is updated.

**Comment by LizBaker** [comment]
closing because the app was EOLed
