### ISSUE TITLE
[nr1-slo-r app] assist Nr labs in deprecating this app `mid-jan`

### ISSUE THREAD

**Issue by jpvajda** [newrelic/nr1-catalog#422]
With the release of Product SLM NR-Labs will start the process of deprecating and removing SLO/R from the apps catalog. NR-Labs will reach out to any existing users and push them towards SLM and work with them on the migration.

### Acceptance Criteria 

- [x] Review the PR for the [migration utility]( https://github.com/newrelic/nr1-slo-r/blob/main/docs/slor_slm_migration.md) when ready.
- [x] upgrade the slo-r update https://github.com/newrelic/nr1-catalog/pull/423
- [ ] Assist NR-Labs in the deprecation of the [SLO-R application](https://github.com/newrelic/nr1-catalog/wiki/New-Relic-One-App-Catalog-How-To-Guide#removing-an-app-from-the-nr1-catalog) from the app catalog. -- need to confirm with @ricegi

**Comment by jpvajda** [comment]
I've merged in the PR to bump nr1-cloud-optimize in the app catalog, and have pinged the core team to upgrade it in EU / staging

**Comment by jpvajda** [comment]
@ricegi do you have a target date of when this app deprecation needs to occur?

**Comment by ricegi** [comment]
I don't have a definitive date, I am still reaching out to active users. I'd assume mid January, that was what was in my mind anyway.

**Comment by jpvajda** [comment]
re-targeting to mid jan.
