### ISSUE TITLE
Create better automation for nr1 apps

### ISSUE THREAD

**Issue by tangollama** [newrelic/nr1-catalog#86]
Create a GitHub action that can be added to NR1 app repos which, on a commit to the release branch (`master` or `main`):

- [x] checks out a branch of THIS repo
- [x] updates that branch's submodule to the latest release hash of the given NR1 app
- [x] submits a PR for a specific commit of that branch to THIS repo's release branch (currently master)

The objective is to automate the release process for permissioned apps (especially NR-owned apps)

**Comment by jbeveland27** [comment]
This was done as a part of releasing [newrelic/nr1-catalog-manager](https://github.com/newrelic/nr1-catalog-manager)
